=== javigarciacespedes/SIBD_P1/banda.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://example.com/banda.schema.json",
	"title": "Banda Validator",
	"type": "object",
	"properties": {
		"group": {
			"type": "string",
			"minLength": 3,
			"maxLength": 50
		},
		"foundation_year": {
			"type": "string",
  			"format": "date"
		},
		"web": {
			"type": "string",
			"format": "uri"
		},
		"email": {
			"type": "string",
			"format": "email"
		},
		"description": {
			"type": "string",
			"minLength": 50,
			"maxLength": 500
		},
		"members": {
			"type": "array",
			"minItems": 2,
			"maxItems": 10,
			"uniqueItems": true,
			"items": [
				{
					"type": "object",
					"properties": {
						"name": { "type": "string"},
						"edad": { "type": "number", "minimum": 0, "maximum": 120}
					}
				}
			]
		},
		"albums": {
			"type": "array",
			"minItems": 1,
			"uniqueItems": true, 
			"items": [
				{
					"type": "object",
					"properties": {
						"name": { "type": "string"},
						"year": { "type": "number", "minimum": 1900, "maximum": 2099},
						"songs": { "type": "array", "items": [
							{
								"type": "object",
								"properties": {
									"name": { "type": "string"},
									"length": { "type": "string", "format": "time"},
									"hit": { "type": "boolean"}
								}
							}
						]}
					}
				}
			]
		},
		"concerts": {
			"type": "array",
			"uniqueItems": true,
			"minItems": 1,
			"maxItems": 20,
			"items": [
				{ "type": "string"}
			]
		}
	},
	"required": ["group", "foundation_year", "web", "email", "description", "members", "albums", "concerts"]
}

=== javigarciacespedes/SIBD_P1/banda.json
{
  "group": "One Direction",
  "foundation_year": "2010-11-12",
  "web": "https://www.onedirectionmusic.com/gb/home.html",
  "email": "javier.garcia.cespedes@alumnos.upm.es",
  "description": "1D fue una boy band brit√°nico-irlandesa formada en 2010 compuesta por Harry Styles, Liam Payne, Zayn Malik, Niall Horan y Louis Tomlinson.",
  "members": [
    { "name": "Harry Styles", "edad": 28 },
    { "name": "Liam Payne", "edad": 29 },
    { "name": "Zayn Malik", "edad": 29 },
    { "name": "Niall Horan", "edad": 29 },
    { "name": "Louis Tomlinson", "edad": 30 }
  ],
  "albums": [
    {"name": "Up All Night", "year": 2011, "songs": [
        {
            "name": "What Makes You Beautiful",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Gotta Be You",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "One Thing",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "More than this",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Up All Nigh",
            "length": "20:20:39+00:00",
            "hit": false
        },
        {
            "name": "I Wish",
            "length": "20:20:39+00:00",
            "hit": false
        },
        {
            "name": "Tell Me a Lie",
            "length": "20:20:39+00:00",
            "hit": false
        },
        {
            "name": "I Want",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Everything About You",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Same Mistakes",
            "length": "20:20:39+00:00",
            "hit": false
        },
        {
            "name": "Save You Tonight",
            "length": "20:20:39+00:00",
            "hit": false
        },
        {
            "name": "Stole My Heart",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Stand Up",
            "length": "20:20:39+00:00",
            "hit": true
        },
        {
            "name": "Moments",
            "length": "20:20:39+00:00",
            "hit": true
        }
    ]},
    {"name": "Take Me Home","year": 2012, "songs": [{
        "name": "Live While We're Young",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Kiss You",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Little Things",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "C'mon C'mon",
        "length": "20:20:39+00:00",
        "hit": false
    },
    {
        "name": "Last First Kiss",
        "length": "20:20:39+00:00",
        "hit": false
    },
    {
        "name": "Heart Attack",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Rock Me",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Change My Mind",
        "length": "20:20:39+00:00",
        "hit": false
    },
    {
        "name": "I Would",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Over Again",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Back For You",
        "length": "20:20:39+00:00",
        "hit": false
    },
    {
        "name": "They Don't Know About Us",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Summer Love",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "She's Not Afraid",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Loved You First",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Nobody Compares",
        "length": "20:20:39+00:00",
        "hit": false
    },
    {
        "name": "Still The One ",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Truly, Madly, Deeply",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Magic",
        "length": "20:20:39+00:00",
        "hit": true
    },
    {
        "name": "Irresistible",
        "length": "20:20:39+00:00",
        "hit": false
    }
]}
],
  "concerts": ["Madrid", "Los Angeles", "Paris", "Berlin", "Nueva York", "Almeria", "Kiev", "Estocolmo"]
}
